---
- name: install collectd packages
  become: yes
  become_method: sudo
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd           # collectd itself
    - libsemanage-python # for managing selinux settings here
  tags:
    - collectd
    - bootstrap

- name: install collectd docker plugin dependencies
  become: yes
  become_method: sudo
  pip:
    executable: /usr/local/bin/pip
    name: "{{ item }}"
    state: present
  with_items:
    - py-dateutil
    - docker-py>=1.0.0
    - six>=1.9.0
  tags:
    - collectd

- name: create collectd config directory
  become: yes
  become_method: sudo
  file:
    path: /etc/collectd.d
    state: directory
    mode: 0755
  tags:
    - collectd

- name: create collectd plugin directory
  become: yes
  become_method: sudo
  file:
    path: /usr/share/collectd/plugins
    state: directory
    mode: 0755
  tags:
  - collectd

- name: configure collectd
  become: yes
  become_method: sudo
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
  notify:
    - restart collectd
  tags:
    - collectd

- name: install collectd docker plugin
  become: yes
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/usr/share/collectd/plugins/{{ item }}"
    mode: 0444
  with_items:
    - dockerplugin.py
    - dockerplugin.db
  tags:
    - collectd

- name: configure collectd docker plugin
  become: yes
  become_method: sudo
  copy:
    src: dockerplugin.conf
    dest: /etc/collectd.d/docker.conf
  notify:
    - restart collectd
  tags:
    - collectd

- name: authorize collectd to make tcp connections
  become: yes
  become_method: sudo
  seboolean: name=collectd_tcp_network_connect state=yes persistent=yes
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode == "enforcing"
  tags:
    - collectd

- name: check if collectd is authorized to connect to docker
  become: yes
  become_method: sudo
  shell: semodule -l
  register: semodule_list
  failed_when: no
  changed_when: no
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode == "enforcing"
  tags:
    - collectd

- name: copy collectd selinux docker policy
  become: yes
  become_method: sudo
  copy: src=collectd_docker_plugin.pp dest=/tmp/collectd_docker_plugin.pp owner=root mode=0600
  when: "semodule_list.stdout is defined and semodule_list.stdout.find('collectd_docker_plugin') == -1"
  tags:
    - collectd

- name: authorize collectd to connect to docker
  become: yes
  become_method: sudo
  shell: semodule -i /tmp/collectd_docker_plugin.pp
  when: "semodule_list.stdout is defined and semodule_list.stdout.find('collectd_docker_plugin') == -1"
  tags:
    - collectd

- name: enable collectd
  become: yes
  become_method: sudo
  service:
    name: collectd
    enabled: yes
    state: started
  tags:
    - collectd
