---

- name: restart zookeeper
  become: yes
  become_method: sudo
  service:
    name: zookeeper-server
    state: restarted
  notify:
    - wait for zookeeper to listen
  tags:
    - zookeeper

- name: wait for zookeeper to listen
  become: yes
  become_method: sudo
  command: "/usr/local/bin/zookeeper-wait-for-listen.sh {{ inventory_hostname }}"
