---

- hosts: mesos
  gather_facts: yes
  roles:
    - common
    - docker
    - weave
    - collectd
    - logrotate
    - consul
    - elasticsearch
    - logstash
    - kibana
    - dnsmasq

- hosts: mesos-master
  vars:
    mesos_mode: master
  roles:
    - zookeeper
    - mesos
    - marathon
    - chronos

- hosts: mesos-slave
  vars:
    mesos_mode: slave
  roles:
    - mesos
    - source

- hosts: proxy
  roles:
    - traefik