---
- name: restart rsyslog
  become: yes
  become_method: sudo
  service: name=rsyslog state=restarted

- name: restart docker
  become: yes
  become_method: sudo
  service: name=docker state=restarted
