---

- name: install docker repo
  become: yes
  become_method: sudo
  template: src=./docker.repo.j2 dest=/etc/yum.repos.d/docker.repo
  tags:
    - docker 

- name: install docker
  become: yes
  become_method: sudo
  yum: name=docker-engine state=present
  tags:
    - docker

# Because AWS Linux only support up to docker 1.7.1, we have to hack it to docker 1.9.0 by doing the following
- name: stop docker
  become: yes
  become_method: sudo
  service: name=docker state=stopped
  ignore_errors: yes
  tags:
    - docker

- name: back up old docker
  become: yes
  become_method: sudo
  command: /bin/cp /usr/bin/docker /usr/bin/docker.old
  tags:
    - docker

- name: download docker 1.9.0 and replace 1.7.1
  become: yes
  become_method: sudo
  get_url: url=https://get.docker.com/builds/Linux/x86_64/docker-1.9.0 dest=/usr/bin/docker force=yes
  tags:
    - docker

- name: set up the configuration file to add cluster store
  become: yes
  become_method: sudo
  template: src=./docker.j2 dest=/etc/sysconfig/docker force=yes
  notify:
    - restart docker
  tags:
    - docker

- name: ensure the docker log directory exist
  become: yes
  become_method: sudo
  file:
    dest: /var/log/docker-container
    state: directory     
  tags:
    - docker
    - rsyslog

- name: create docker entry for syslogd
  become: yes
  become_method: sudo
  copy:
    dest: /etc/rsyslog.d/10-docker.conf
    content: |
      # Docker logging
      :syslogtag, startswith, "docker" -/var/log/docker-container/docker.log
      & ~      
  notify:
    - restart rsyslog
  tags:
    - docker
    - rsyslog

- name: start docker
  become: yes
  become_method: sudo
  service: name=docker state=started enabled=yes
  tags:
    - docker

- name: add cron job to clear exited containers every 1 hour
  become: yes
  become_method: sudo
  cron: name="docker-clearer" minute="0" job="docker rm $(docker ps -aq --filter='status=exited')"
  tags:
    - docker
    - docker-clearer

- name: add cron job to clear dangling images every 1 day
  become: yes
  become_method: sudo
  cron: name="docker-image-clearer" hour="0" job="docker rmi $(docker images -q --filter 'dangling=true')"
  tags:
    - docker
    - docker-clearer

- name: create docker group
  become: yes
  become_method: sudo
  group: name=docker state=present
  tags:
    - docker

- name: add user to docker
  become: yes
  become_method: sudo
  user: name=ec2-user group=docker append=yes
  tags:
    - docker

- name: pull spark-mesos images
  become: yes
  become_method: sudo
  shell: docker pull wumuxian/spark-mesos:1.6.0-0.27.0
  tags:
    - docker

- name: pull jupyter-spark-mesos images
  become: yes
  become_method: sudo
  run_once: true
  delegate_to: mesos-master1
  shell: docker pull wumuxian/jupyter-spark-mesos
  tags:
    - docker