---

- name: update the rsyslog config
  become: yes
  become_method: sudo
  template: src=./rsyslog_mesos.conf.j2 dest=/etc/rsyslog.d/mesos.conf
  tags:
    - rsyslog 
    - common

- name: restart rsyslog
  become: yes
  become_method: sudo
  service: name=rsyslog state=restarted
  tags:
    - rsyslog
    - common