---
consul_dns_domain: consul
# right now there is an issue with chronos zookeeper connection with auth, so leave it blank for now
chronos_zk_auth: ""
chronos_zk_dns: "zookeeper.service.{{ consul_dns_domain }}"
chronos_zk_port: 2181
chronos_zk_chroot: chronos
chronos_zk_connect: "zk://{{chronos_zk_auth}}{{ chronos_zk_dns }}:{{ chronos_zk_port }}/{{chronos_zk_chroot}}"

chronos_zk_mesos_master: "zk://{{ chronos_zk_dns }}:{{ chronos_zk_port }}/mesos"

# zookeeper
chronos_zk_acl_world: "world:anyone:cdrwa"
chronos_zk_acl: "{% if zk_chronos_user_secret is defined %}digest:{{ zk_chronos_user }}:{{ zk_chronos_user_secret_digest}}:cdraw{% endif  %}"

chronos_zk_acl_cmd: "zookeepercli -servers localhost:{{ chronos_zk_port }} -auth_usr='super' -auth_pwd='{{ zk_super_user_secret }}' -force -c setacl /{{ chronos_zk_chroot }} '{{ chronos_zk_acl_world }},{{ chronos_zk_acl }}'"

chronos_image_name: mesosphere/chronos
chronos_image_tag: chronos-2.4.0-0.1.20150828104228.ubuntu1404-mesos-0.27.0-0.2.190.ubuntu1404
chronos_port: 8081
# framework authentication
