---

- name: download consul-cli
  become: yes
  become_method: sudo
  unarchive: src=https://github.com/CiscoCloud/consul-cli/releases/download/v0.1.1/consul-cli_0.1.1_linux_amd64.tar.gz dest=./ copy=false
  tags:
    - consul 
    - consul-cli

- name: install consul-cli
  become: yes
  become_method: sudo
  shell: mv consul-cli_0.1.1_linux_amd64/consul-cli /usr/bin/consul-cli
  tags:
    - consul
    - consul-cli

- name: remove consul-cli tar ball
  become: yes
  become_method: sudo
  file: path=consul-cli_0.1.1_linux_amd64 state=absent 
  tags:
    - consul
    - consul-cli